### ISSUE TITLE
Should I train lossnet_train.py with my datasets ?

### ISSUE THREAD

**Issue by ucasiggcas** [francoisgermain/SpeechDenoisingWithDeepFeatureLosses#7]
Dear,

If I use my own data,should I run lossnet_train.py ?

Thx.

**Comment by ucasiggcas** [comment]
If I directly run 
`python senet_train.py -d folder_name -l loss_folder -o out_folder`
it ups bug,
`Traceback (most recent call last):
  File "senet_train.py", line 89, in <module>
    loss_saver.restore(sess, "./%s/loss_model.ckpt" % modfolder)
  File "D:\python\lib\site-packages\tensorflow\python\training\saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: ./loss_folder/loss_model.ckpt`

**Comment by ucasiggcas** [comment]
and if I run
`python lossnet_train.py -o out_folder`
it also tells me
`Traceback (most recent call last):
  File "lossnet_train.py", line 50, in <module>
    load_asc_data("dataset/asc/")
  File "D:\python\SpeechDenoisingWithDeepFeatureLosses-master\data_import.py", line 126, in load_asc_data
    with open('%s/meta.txt' % foldername, 'rb') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/asc//trainset/meta.txt'`

so how to solve the problem ?
Thx

**Comment by ucasiggcas** [comment]
When I run the code
`python lossnet_train.py` on ubuntu 18.04
it also have the same problem
`Traceback (most recent call last):
  File "lossnet_train.py", line 50, in <module>
    load_asc_data("dataset/asc/")
  File "/root/SpeechDenoisingWithDeepFeatureLosses/data_import.py", line 126, in load_asc_data
    with open('%s/meta.txt' % foldername, 'rb') as csvfile:
IOError: [Errno 2] No such file or directory: 'dataset/asc//trainset/meta.txt'`

so what's wrong ?

**Comment by zeynepgulhanuslu** [comment]
I've changed the code like this :  "open('%s/meta.txt' % foldername, 'r') " end it worked for me:) And also you should have a meta.txt file in that folder.

**Comment by ucasiggcas** [comment]
> I've changed the code like this : "open('%s/meta.txt' % foldername, 'r') " end it worked for me:) And also you should have a meta.txt file in that folder.

where is the meta.txt file ? Or how to write the file ?
how to set ?
No details.

**Comment by zeynepgulhanuslu** [comment]
I'm no expert but i created meta.txt file myself. I think you should create it for your dataset. The file contains wav file path and its label. For example;
audio/003/012.wav car noise
audio/923/42.wav white noise
audio/234/11.wav white noise
..
etc. It could contain more than one file for a noise. I've put meta.txt files in trainset and valset folders. At least i could train my dataset this way. I don't know for sure this is the exact solution:) You can try :)

**Comment by TeerathChandani** [comment]
I have noisy and clean wave files. Each has two channel. I want to train on it. Is there any modification I have to do?

like 32-float, Sample rate changing or model input?

Thanks,
